version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest

  build_and_push_docker_image:
    docker:
      - image: docker:latest

    working_directory: /app

    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t deepthi29/sparse-docker:latest .
      
      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "Saireddy@29" | docker login -u "deepthi29" --password-stdin
            docker push deepthi29/latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_and_push_docker_image:
          requires:
            - build
