version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.8

    working_directory: /app

    steps:
      - checkout

      # Setup remote Docker environment
      - setup_remote_docker

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t deepthi29/sparse-docker:latest .
      
      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push deepthi29/sparse-docker:latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_and_push_docker_image:
          requires:
            - build
