version: 2.1

jobs:
  build and push to dockerhub:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

      - run:
          name: "Install Dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: "Run Tests"
          command: pytest

      - setup_remote_docker

      - run:
          name: "Build Docker Image"
          command: |
            docker build -t deepthi29/sparse__docker:v1 .

      - run:
          name: "Push Docker Image"
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push deepthi29/sparse__docker:v1

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build and push to dockerhub:
          filters:
            branches:
              only:
                - main
