version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8  # Use the Python version you need
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build:
    jobs:
      - build

