version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            pytest

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t deepthi29/sparse-docker .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: |
            echo "Saireddy@123" | docker login -u "deepthi29" --password-stdin

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push deepthi29/sparse-docker

workflows:
  version: 2
  build:
    jobs:
      - build
