version: 2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build:
    jobs:
      - build
