version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t sparse-docker .
      
      # Run tests inside Docker container
      - run:
          name: Run tests
          command: |
            docker run -it sparse-docker

workflows:
  version: 2
  build:
    jobs:
      - build
